"""add cod_cli em contratos_cabecalho

Revision ID: 1f3cebbed642
Revises: 5e7e2dde172f
Create Date: 2025-08-22 17:08:20.700972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f3cebbed642'
down_revision: Union[str, Sequence[str], None] = '5e7e2dde172f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_column('contratos', 'valor_presente')
    op.add_column('contratos_cabecalho', sa.Column('cod_cli', sa.String(), nullable=True))
    op.create_index(op.f('ix_contratos_cabecalho_cod_cli'), 'contratos_cabecalho', ['cod_cli'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contratos_cabecalho_cod_cli'), table_name='contratos_cabecalho')
    op.drop_column('contratos_cabecalho', 'cod_cli')
    op.add_column('contratos', sa.Column('valor_presente', sa.REAL(), nullable=True))
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=1)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###
