"""models v1.7.3 (cod_cli cabeçalho / índices explícitos)

Revision ID: 2f9dbfc324ad
Revises: 1f3cebbed642
Create Date: 2025-08-22 17:42:18.104465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f9dbfc324ad'
down_revision: Union[str, Sequence[str], None] = '1f3cebbed642'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
